# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxExercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxExercise
  # RxSwift
  pod 'RxSwift', '~> 6.6.0'
  pod 'RxCocoa', '~> 6.6.0'

end
